#!/bin/sh

set -e
if ! getent group | grep -q libuuid; then
groupadd -f -K GID_MIN=1 -K GID_MAX=999 libuuid
fi
if ! getent passwd | grep -q libuuid; then
   useradd -d /var/lib/libuuid -K UID_MIN=1 -K UID_MAX=499 -g libuuid libuuid
fi
chown libuuid:libuuid /usr/sbin/uuidd
chmod 6755 /usr/sbin/uuidd

#DEBHELPER#

# The service is socket-activated under systemd, start it otherwise.
if [ ! -d /run/systemd/system/ ] && [ -x /etc/init.d/uuidd ]; then
	invoke-rc.d uuidd start
fi

exit 0
